name: RideMeshIOS
options:
  bundleIdPrefix: com.autopilotindia
  deploymentTarget:
    iOS: "16.0"
packages:
  WebRTC:
    url: https://github.com/stasel/WebRTC.git
    exactVersion: 152.0.0
targets:
  RideMeshIOS:
    type: application
    platform: iOS
    deploymentTarget: "16.0"
    sources:
      - path: RideMeshIOS
        excludes:
          - Hybrid/**
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.autopilotindia.ridemesh
        PRODUCT_NAME: RideMesh
        SWIFT_VERSION: 5.0
        SWIFT_STRICT_CONCURRENCY: targeted
        MARKETING_VERSION: "1.7"
        CURRENT_PROJECT_VERSION: "37"
        CODE_SIGN_ENTITLEMENTS: RideMeshIOS/RideMeshIOS.entitlements
        INFOPLIST_FILE: RideMeshIOS/Info.plist
        TARGETED_DEVICE_FAMILY: "1"
        CODE_SIGN_STYLE: Automatic
    dependencies:
      - package: WebRTC
schemes:
  RideMeshIOS:
    build:
      targets:
        RideMeshIOS: all
    run:
      config: Debug
