from pathlib import Path
import re

p = Path('app/src/main/java/com/bikemesh/ridemesh/MainActivity.kt')
s = p.read_text()

# The Beta4.5 panel helper is intentionally generated by the prior patch step.
# Normalize only that helper region: its first draft used literal \\n tokens.
start_marker = '    private fun panelCardBackground'
end_marker = '    private fun showRidersDialog() {'
start = s.find(start_marker)
end = s.find(end_marker, start)
if start < 0 or end < 0:
    raise SystemExit('Beta4.5 helper region not found')

helper = s[start:end]
helper = helper.replace('\\n', '\n')
s = s[:start] + helper + s[end:]

# Rider-name editor uses InputType.
if 'import android.text.InputType\n' not in s:
    anchor = 'import android.os.Looper\n'
    if anchor not in s:
        raise SystemExit('InputType import anchor not found')
    s = s.replace(anchor, anchor + 'import android.text.InputType\n', 1)

# Avoid escaping ambiguity in the generated email local-part parser.
s, count = re.subn(
    r'''val words = local\.split\(Regex\(".*?"\)\)\.filter \{ it\.isNotBlank\(\) \}''',
    "val words = local.split(' ').filter { it.isNotBlank() }",
    s,
    count=1,
)
if count != 1:
    raise SystemExit(f'rider-name split normalization count={count}')

p.write_text(s)
print('Beta4.5 generated Kotlin normalized')
